<?php

namespace app\components;
use yii\base\Widget;

class MyWidget extends Widget
{
    public $name;
    public function init()
    {
        parent::init();
        if ($this->name === null) $this->name = "Гость";
        // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('my', ['name'=>$this->name]); // TODO: Change the autogenerated stub
    }
}