<?php

namespace app\models;

use yii\behaviors\OptimisticLockBehavior;
use yii\db\ActiveRecord;

class RecordModel extends ActiveRecord
{
    public static function tableName()
    {
        return 'records'; // TODO: Change the autogenerated stub
    }
    public function behaviors()
    {
        return [
            OptimisticLockBehavior::class,
        ];
    }

    public function optimisticLock()
    {
        return 'version';
    }

    public function AttributeLabels()
    {
        return [
            "id" => "ID",
            "text" => "Текст",
            "version" => "Версия"
        ];
    }


}